version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/ui/'
      schedule:
          interval: 'monthly'
      groups:
        all-dependencies:
          patterns:
            - "*"
      versioning-strategy: 'increase-if-necessary'
      open-pull-requests-limit: 3
      ignore:
          - dependency-name: '*'
            update-types:
                ['version-update:semver-major', 'version-update:semver-patch']